### Obtener todos los contactos
GET http://localhost:3000/contacts

### Obtener un contacto por ID (Reemplaza el ID de abajo con uno real de tu base de datos)
GET http://localhost:3000/contacts/AQUI_VA_TU_ID_REAL